### ISSUE TITLE
RN 0.66.5 + SES 0.18.4: `Unable to resolve module ./debugger-ui/debuggerWorker.x.js` thread

### ISSUE THREAD

**Issue by leotm** [LavaMoat/docs#22]
only w Chrome DevTools opened

<img width="2056" alt="Screenshot 2023-07-12 at 11 55 56" src="https://github.com/LavaMoat/docs/assets/1881059/a174b76f-7c02-4b21-a287-d20253508822">

```console
 MAP  ./index.js

 BUNDLE  ./index.js

Error: Unable to resolve module ./debugger-ui/debuggerWorker.aca173c4.js from /Users/leo/Documents/GitHub/metamask-mobile/.:

None of these files exist:
  * debugger-ui/debuggerWorker.aca173c4.js(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg|.native.cjs|.cjs)
  * debugger-ui/debuggerWorker.aca173c4.js/index(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg|.native.cjs|.cjs)
    at ModuleResolver.resolveDependency (/Users/leo/Documents/GitHub/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:107:15)
    at DependencyGraph.resolveDependency (/Users/leo/Documents/GitHub/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at /Users/leo/Documents/GitHub/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/lib/transformHelpers.js:129:24
    at Server._resolveRelativePath (/Users/leo/Documents/GitHub/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:1072:12)
    at async Server.requestProcessor [as _processSourceMapRequest] (/Users/leo/Documents/GitHub/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:428:37)
    at async Server._processRequest (/Users/leo/Documents/GitHub/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:389:7)
 BUNDLE  ./index.js

 MAP  ./index.js

 LOG  JavaScript logs will appear in your browser console
```

error log sometimes included in Local scope `_ref` prop

<img width="459" alt="Screenshot 2023-07-12 at 12 37 22" src="https://github.com/LavaMoat/docs/assets/1881059/c3ac7908-a09a-49be-850b-54a6fce25557">

<img width="1031" alt="Screenshot 2023-07-12 at 12 37 50" src="https://github.com/LavaMoat/docs/assets/1881059/36d44cbf-189d-4c13-af80-5e8521dd2369">

**Comment by leotm** [comment]
actually this is unrelated to SES

raise in `metamask-mobile` or `mobile-planning`
if still occuring post-RN 0.71.x, once merged into https://github.com/MetaMask/metamask-mobile/pull/6586

no visible debugging degradation, despite error
